server:
  application:
    name: wxz-admin
  port: 80
  context-path: /wxz-admin

mysql:
  datasource:
    write:
      url: jdbc:mysql://127.0.0.1:3306/wxz-zone?useUnicode=true&amp;characterEncoding=utf8
      username: root
      password: root
    read01:
      url: jdbc:mysql://127.0.0.1:3306/wxz-zone?useUnicode=true&amp;characterEncoding=utf8
      username: root
      password: root
    read02:
      url: jdbc:mysql://127.0.0.1:3306/wxz-zone?useUnicode=true&amp;characterEncoding=utf8
      username: root
      password: root



