server:
  application:
    name: wxz-zone
  port: 8080
  context-path: /wxz-zone
mysql:
  datasource:
    write:
      url: jdbc:mysql://47.88.220.111:3306/wxz-zone?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: root
    read:
      url: jdbc:mysql://47.88.220.111:3306/wxz-zone?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: root


