server:
  application:
    name: wxz-zone
  port: 8088
  context-path: /wxz-zone

mysql:
  datasource:
    write:
      url: jdbc:mysql://47.88.220.111:3306/wxz-zone?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: root
    read01:
      url: jdbc:mysql://47.88.220.111:3306/wxz-zone?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: root
    read02:
      url: jdbc:mysql://47.88.220.111:3306/wxz-zone?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: root



